name: doppler_rain_radar
description: Live Doppler Rain Radar & Hurricane Tracker with automated Rewarded Ad unlocking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.0
  google_mobile_ads: ^5.1.0
  cupertino_icons: ^1.0.6
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
